apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-credentials-decoy
  namespace: default
data:
  credentials: |
    [default]
    aws_access_key_id = AKIAFAKEIOSFODNN7EXAMPLE
    aws_secret_access_key = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
