apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 7.3.11 
    chart: grafana
    helm:
      values: |
      
        image:
          tag: "10.4.2"

      
        env:
          GF_PLUGINS_PREINSTALL: "neo4j-datasource"

        adminPassword: "ChangeMePlease!"

        persistence:
          enabled: true
          size: 1Gi

        service:
          type: ClusterIP

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'monitoring' 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
