apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.n8n.io/'
    targetRevision: 0.40.1 
    chart: n8n
    helm:
      values: |
        # Basic configuration for n8n
        # It will use a simple SQLite database internally
        # which is perfect for our zero-cost project.
        service:
          type: ClusterIP
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
