apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pomerium
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.pomerium.io'
    targetRevision: 41.1.0 
    chart: pomerium
    helm:
      values: |
       
      authenticate:
          url: "https://authenticate.pomerium.localhost"

       
        config:
          sharedSecret: "PASTE_YOUR_FIRST_SECRET_HERE"
          cookieSecret: "PASTE_YOUR_SECOND_SECRET_HERE"

        
        proxy:
          service:
            type: ClusterIP

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'pomerium' 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
