apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: 0.27.0
    chart: vault
    helm:
      values: |
        ui:
          enabled: true
        server:
          standalone:
            enabled: true
          dataStorage:
            enabled: true
            size: 1Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default' 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true